# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Answer(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, code: str=None, text: str=None):
        """
        Answer - a model defined in Swagger

        :param code: The code of this Answer.
        :type code: str
        :param text: The text of this Answer.
        :type text: str
        """
        self.swagger_types = {
            'code': str,
            'text': str
        }

        self.attribute_map = {
            'code': 'code',
            'text': 'text'
        }

        self._code = code
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'Answer':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Answer of this Answer.
        :rtype: Answer
        """
        return deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """
        Gets the code of this Answer.

        :return: The code of this Answer.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """
        Sets the code of this Answer.

        :param code: The code of this Answer.
        :type code: str
        """

        self._code = code

    @property
    def text(self) -> str:
        """
        Gets the text of this Answer.

        :return: The text of this Answer.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """
        Sets the text of this Answer.

        :param text: The text of this Answer.
        :type text: str
        """

        self._text = text

